export const FAMILLES_SUCCES = {
  collection: { nom: 'Collection', motif: 'plume', teinte: '#cbb996' },
  paquets: { nom: 'Paquets', motif: 'cristal', teinte: '#97cddd' },
  raretes: { nom: 'Raretés', motif: 'etoiles', teinte: '#c7b0eb' },
  finitions: { nom: 'Finitions', motif: 'papillon', teinte: '#9adfcf' },
  duels: { nom: 'Duels', motif: 'phenix', teinte: '#e9ad91' },
  joutes: { nom: 'Joutes', motif: 'dragon', teinte: '#a5d5b6' },
  savoir: { nom: 'Savoir', motif: 'oracle', teinte: '#b1c7ef' },
  exploration: { nom: 'Exploration', motif: 'boussole', teinte: '#d7bdd8' },
} as const;
export type FamilleSucces = keyof typeof FAMILLES_SUCCES;
export type MesureSucces = 'collection' | 'paquets' | 'rares' | 'epiques' | 'legendaires' | 'horsSerie' | 'brillantes' | 'holographiques' | 'triptyques' | 'duels' | 'victoires' | 'joutes' | 'victoiresJoutes' | 'definitions' | 'parades' | 'maitrises' | 'origines' | 'natures' | 'longs' | 'courts' | 'raretes';
export type Succes = { id: string; nom: string; description: string; titre: string; famille: FamilleSucces; mesure: MesureSucces; objectif: number };

// Un succès, un titre. Aucun titre ne s'achète et aucun ne dépend d'une formule payante.
export const SUCCES: readonly Succes[] = [
  { id: 'premier-mot', nom: 'Une place dans l’album', description: 'Réunir 1 mot distinct dans l’album.', titre: 'Esprit curieux', famille: 'collection', mesure: 'collection', objectif: 1 },
  { id: 'dix-mots', nom: 'Le début d’une histoire', description: 'Réunir 10 mots distincts dans l’album.', titre: 'Cueilleur de mots', famille: 'collection', mesure: 'collection', objectif: 10 },
  { id: 'vingt-cinq-mots', nom: 'De page en page', description: 'Réunir 25 mots distincts dans l’album.', titre: 'Tourneur de pages', famille: 'collection', mesure: 'collection', objectif: 25 },
  { id: 'cinquante-mots', nom: 'L’album prend vie', description: 'Réunir 50 mots distincts dans l’album.', titre: 'Relieur d’histoires', famille: 'collection', mesure: 'collection', objectif: 50 },
  { id: 'cent-mots', nom: 'Cent nuances de langue', description: 'Réunir 100 mots distincts dans l’album.', titre: 'Arpenteur de mots', famille: 'collection', mesure: 'collection', objectif: 100 },
  { id: 'deux-cent-cinquante-mots', nom: 'Une bibliothèque de poche', description: 'Réunir 250 mots distincts dans l’album.', titre: 'Bibliothécaire nomade', famille: 'collection', mesure: 'collection', objectif: 250 },
  { id: 'cinq-cents-mots', nom: 'Les murs du cabinet', description: 'Réunir 500 mots distincts dans l’album.', titre: 'Conservateur du verbe', famille: 'collection', mesure: 'collection', objectif: 500 },
  { id: 'mille-mots', nom: 'Mille et un possibles', description: 'Réunir 1 000 mots distincts dans l’album.', titre: 'Mémoire des mondes', famille: 'collection', mesure: 'collection', objectif: 1000 },
  { id: 'premier-paquet', nom: 'Briser le sceau', description: 'Ouvrir 1 paquet.', titre: 'Ouvreur de possibles', famille: 'paquets', mesure: 'paquets', objectif: 1 },
  { id: 'dix-paquets', nom: 'Courrier régulier', description: 'Ouvrir 10 paquets.', titre: 'Correspondant assidu', famille: 'paquets', mesure: 'paquets', objectif: 10 },
  { id: 'vingt-cinq-paquets', nom: 'Le bruissement du papier', description: 'Ouvrir 25 paquets.', titre: 'Complice du hasard', famille: 'paquets', mesure: 'paquets', objectif: 25 },
  { id: 'cent-paquets', nom: 'La malle aux surprises', description: 'Ouvrir 100 paquets.', titre: 'Facteur de merveilles', famille: 'paquets', mesure: 'paquets', objectif: 100 },
  { id: 'deux-cent-cinquante-paquets', nom: 'La grande correspondance', description: 'Ouvrir 250 paquets.', titre: 'Maître des sceaux', famille: 'paquets', mesure: 'paquets', objectif: 250 },
  { id: 'premier-rare', nom: 'Un mot qui se distingue', description: 'Réunir 1 timbre Rare.', titre: 'Chasseur de nuances', famille: 'raretes', mesure: 'rares', objectif: 1 },
  { id: 'dix-rares', nom: 'Le goût du singulier', description: 'Réunir 10 timbres Rares distincts.', titre: 'Amateur de singularités', famille: 'raretes', mesure: 'rares', objectif: 10 },
  { id: 'premier-epique', nom: 'Au-delà du quotidien', description: 'Réunir 1 timbre Épique.', titre: 'Découvreur d’insolite', famille: 'raretes', mesure: 'epiques', objectif: 1 },
  { id: 'dix-epiques', nom: 'Le cabinet des curiosités', description: 'Réunir 10 timbres Épiques distincts.', titre: 'Gardien des curiosités', famille: 'raretes', mesure: 'epiques', objectif: 10 },
  { id: 'premier-legendaire', nom: 'L’encre des légendes', description: 'Réunir 1 timbre Légendaire.', titre: 'Témoin de l’exception', famille: 'raretes', mesure: 'legendaires', objectif: 1 },
  { id: 'cinq-legendaires', nom: 'Une constellation de légendes', description: 'Réunir 5 timbres Légendaires distincts.', titre: 'Veilleur des étoiles', famille: 'raretes', mesure: 'legendaires', objectif: 5 },
  { id: 'premier-hors-serie', nom: 'Hors des sentiers battus', description: 'Réunir 1 timbre Hors-série.', titre: 'Passeur de l’extraordinaire', famille: 'raretes', mesure: 'horsSerie', objectif: 1 },
  { id: 'premiere-brillante', nom: 'Un éclat sur le papier', description: 'Réunir 1 timbre en finition Brillante.', titre: 'Éclaireur d’encre', famille: 'finitions', mesure: 'brillantes', objectif: 1 },
  { id: 'dix-brillantes', nom: 'L’album scintillant', description: 'Réunir 10 mots distincts en finition Brillante.', titre: 'Orfèvre du papier', famille: 'finitions', mesure: 'brillantes', objectif: 10 },
  { id: 'premiere-holographique', nom: 'La lumière change de sens', description: 'Réunir 1 timbre Holographique.', titre: 'Prismaturge', famille: 'finitions', mesure: 'holographiques', objectif: 1 },
  { id: 'cinq-holographiques', nom: 'Reflets d’un autre monde', description: 'Réunir 5 mots distincts en finition Holographique.', titre: 'Tisseur de reflets', famille: 'finitions', mesure: 'holographiques', objectif: 5 },
  { id: 'trois-finitions', nom: 'Un mot, trois visages', description: 'Posséder un même mot dans les trois finitions.', titre: 'Triptyquiste', famille: 'finitions', mesure: 'triptyques', objectif: 1 },
  { id: 'premier-duel', nom: 'Entrer dans la danse', description: 'Terminer 1 duel, entraînement ou joute.', titre: 'Plume engagée', famille: 'duels', mesure: 'duels', objectif: 1 },
  { id: 'dix-duels', nom: 'Le plaisir de la réplique', description: 'Terminer 10 duels, entraînements et joutes confondus.', titre: 'Bretteur de syllabes', famille: 'duels', mesure: 'duels', objectif: 10 },
  { id: 'cinquante-duels', nom: 'Une plume aguerrie', description: 'Terminer 50 duels, entraînements et joutes confondus.', titre: 'Vétéran de l’encrier', famille: 'duels', mesure: 'duels', objectif: 50 },
  { id: 'premiere-victoire', nom: 'Le dernier mot', description: 'Remporter 1 duel.', titre: 'Fine lame', famille: 'duels', mesure: 'victoires', objectif: 1 },
  { id: 'dix-victoires', nom: 'La force de la formule', description: 'Remporter 10 duels.', titre: 'Stratège du verbe', famille: 'duels', mesure: 'victoires', objectif: 10 },
  { id: 'cinquante-victoires', nom: 'La plume fait loi', description: 'Remporter 50 duels.', titre: 'Autorité lexicale', famille: 'duels', mesure: 'victoires', objectif: 50 },
  { id: 'cent-victoires', nom: 'Cent fois le dernier mot', description: 'Remporter 100 duels.', titre: 'Souverain des répliques', famille: 'duels', mesure: 'victoires', objectif: 100 },
  { id: 'premiere-joute', nom: 'Au-devant des autres', description: 'Terminer 1 joute classée.', titre: 'Plume du dehors', famille: 'joutes', mesure: 'joutes', objectif: 1 },
  { id: 'dix-joutes', nom: 'Habitué de la lice', description: 'Terminer 10 joutes classées.', titre: 'Ambassadeur de l’encre', famille: 'joutes', mesure: 'joutes', objectif: 10 },
  { id: 'premiere-victoire-joute', nom: 'Faire ses preuves', description: 'Remporter 1 joute classée.', titre: 'Challenger des mots', famille: 'joutes', mesure: 'victoiresJoutes', objectif: 1 },
  { id: 'vingt-cinq-victoires-joutes', nom: 'Le nom que l’on retient', description: 'Remporter 25 joutes classées.', titre: 'Héraut du lexique', famille: 'joutes', mesure: 'victoiresJoutes', objectif: 25 },
  { id: 'premiere-definition', nom: 'Trouver le sens', description: 'Retrouver 1 définition de son propre mot en duel.', titre: 'Déchiffreur', famille: 'savoir', mesure: 'definitions', objectif: 1 },
  { id: 'vingt-cinq-definitions', nom: 'Entre les lignes', description: 'Retrouver 25 définitions de ses propres mots en duel.', titre: 'Lecteur de l’invisible', famille: 'savoir', mesure: 'definitions', objectif: 25 },
  { id: 'cent-definitions', nom: 'Les mots n’ont plus de secrets', description: 'Retrouver 100 définitions de ses propres mots en duel.', titre: 'Interprète du lexique', famille: 'savoir', mesure: 'definitions', objectif: 100 },
  { id: 'premiere-parade', nom: 'Bien entendu', description: 'Réussir 1 parade en reconnaissant le mot adverse.', titre: 'Oreille affûtée', famille: 'savoir', mesure: 'parades', objectif: 1 },
  { id: 'vingt-cinq-parades', nom: 'Lire dans le jeu adverse', description: 'Réussir 25 parades.', titre: 'Déjoueur de pièges', famille: 'savoir', mesure: 'parades', objectif: 25 },
  { id: 'cent-parades', nom: 'Le rempart du sens', description: 'Réussir 100 parades.', titre: 'Sentinelle des définitions', famille: 'savoir', mesure: 'parades', objectif: 100 },
  { id: 'premiere-maitrise', nom: 'Un mot pour toujours', description: 'Maîtriser 1 mot.', titre: 'Encre indélébile', famille: 'savoir', mesure: 'maitrises', objectif: 1 },
  { id: 'vingt-cinq-maitrises', nom: 'Le savoir prend racine', description: 'Maîtriser 25 mots distincts.', titre: 'Gardien du lexique', famille: 'savoir', mesure: 'maitrises', objectif: 25 },
  { id: 'trois-origines', nom: 'Premières escales', description: 'Réunir des mots de 3 origines différentes.', titre: 'Voyageur des racines', famille: 'exploration', mesure: 'origines', objectif: 3 },
  { id: 'huit-origines', nom: 'La langue est un voyage', description: 'Réunir des mots de 8 origines différentes.', titre: 'Cartographe des langues', famille: 'exploration', mesure: 'origines', objectif: 8 },
  { id: 'quatre-natures', nom: 'Toute une grammaire', description: 'Réunir un nom, un verbe, un adjectif et un adverbe.', titre: 'Architecte de phrases', famille: 'exploration', mesure: 'natures', objectif: 4 },
  { id: 'dix-mots-longs', nom: 'Les grands déploiements', description: 'Réunir 10 mots distincts d’au moins 12 lettres.', titre: 'Dérouleur de syllabes', famille: 'exploration', mesure: 'longs', objectif: 10 },
  { id: 'dix-mots-courts', nom: 'L’art de faire court', description: 'Réunir 10 mots distincts de 4 lettres ou moins.', titre: 'Miniaturiste', famille: 'exploration', mesure: 'courts', objectif: 10 },
  { id: 'six-raretes', nom: 'Toutes les nuances de l’album', description: 'Réunir au moins un timbre de chacune des six raretés.', titre: 'Collectionneur sans frontières', famille: 'exploration', mesure: 'raretes', objectif: 6 },
];
export const titreDuSucces = (id: string): string => `titre-${id}`;
export const succesDuTitre = (id: string): Succes | undefined => SUCCES.find(s => titreDuSucces(s.id) === id);
